# ==============================================================================
# Script 138
# Integrated publication-quality figures
# Blood transcriptomic endotypes and biomarker signatures in sepsis
#
# Project: Sepsis_DESeq2
#
# PURPOSE
# Assemble publication-quality, color-consistent figures from validated
# results generated by Scripts 135, 136, 136b and 137.
#
# IMPORTANT
# - NO new feature selection
# - NO new biomarker discovery
# - NO urine
# - NO lncRNA
# - NO new prediction model
# - inferential results are taken from previous validated analyses
#
# MAIN FIGURES
#
# Figure 1
#   Five-gene host-response signature
#
# Figure 2
#   Hierarchical SRS / CTS endotype architecture
#
# Figure 3
#   Five-gene expression heatmap across ordered sepsis endotypes
#
# Figure 4
#   Clinical context
#
# Figure 5
#   Cross-signature convergence
#
# SUPPLEMENTARY
#   S1 demographic sensitivity
#   S2 contextual AUC benchmarking
#   S3 predefined biomarker-gene direction audit
#   S4 all biomarker signatures across CTS
# ==============================================================================


# ==============================================================================
# 0. SETTINGS
# ==============================================================================

options(stringsAsFactors = FALSE)

project_dir <- Sys.getenv("SEPSIS_PROJECT_DIR", unset = path.expand("~/Sepsis_DESeq2"))

if (!dir.exists(project_dir)) {
  stop(
    paste0(
      "Project directory does not exist: ",
      project_dir
    )
  )
}

setwd(project_dir)

script_name <- "138_blood_endotype_integrated_figures.R"
run_date <- Sys.time()

cat("\n")
cat("====================================================================\n")
cat("Running Script 138\n")
cat("Integrated publication-quality blood endotype figures\n")
cat("====================================================================\n\n")

cat("Project directory:\n")
cat(
  normalizePath(
    getwd(),
    winslash = "/",
    mustWork = FALSE
  ),
  "\n\n"
)

cat("Run date:\n")
cat(
  as.character(run_date),
  "\n\n"
)


# ==============================================================================
# 1. PACKAGES
# ==============================================================================

required_packages <- c(
  "dplyr",
  "tidyr",
  "tibble",
  "ggplot2",
  "patchwork",
  "pheatmap"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    logical(1),
    quietly = TRUE
  )
]

if (length(missing_packages) > 0) {
  
  stop(
    paste0(
      "Missing required packages:\n",
      paste(
        missing_packages,
        collapse = ", "
      )
    )
  )
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(ggplot2)
  library(patchwork)
  library(pheatmap)
})

cat("Required packages loaded successfully.\n\n")


# ==============================================================================
# 2. PUBLICATION COLOR PALETTE
# ==============================================================================

condition_colors <- c(
  "BC" = "#4DBBD5",
  "BP" = "#E64B35"
)

srs_colors <- c(
  "SRS1" = "#D55E00",
  "SRS2" = "#0072B2"
)

cts_colors <- c(
  "CTS1" = "#E69F00",
  "CTS2" = "#56B4E9",
  "CTS3" = "#009E73"
)

integrated_colors <- c(
  "CTS1/SRS1" = "#D55E00",
  "CTS2/SRS1" = "#E69F00",
  "CTS3/SRS1" = "#56B4E9",
  "CTS3/SRS2" = "#0072B2"
)

signature_colors <- c(
  "Primary 5-gene" = "#D55E00",
  "DCAF17 alternative" = "#CC79A7",
  "LIFTS-like" = "#009E73",
  "Sepsis MetaScore-like" = "#0072B2",
  "FAIM3:PLAC8-like" = "#E69F00",
  "PLAC8-PLA2G7 contrast" = "#56B4E9",
  "SeptiCyte LAB-like" = "#7F7F7F"
)

gene_direction_colors <- c(
  "UP" = "#D55E00",
  "DOWN" = "#0072B2"
)

significance_colors <- c(
  "FDR < 0.05" = "#D55E00",
  "Nominal p < 0.05" = "#E69F00",
  "NS" = "#999999"
)


# ==============================================================================
# 3. PUBLICATION THEME
# ==============================================================================

theme_manuscript <- function(
    base_size = 11
) {
  
  theme_bw(
    base_size = base_size
  ) +
    
    theme(
      
      plot.title =
        element_text(
          face = "bold",
          size = base_size + 2
        ),
      
      plot.subtitle =
        element_text(
          size = base_size
        ),
      
      strip.text =
        element_text(
          face = "bold"
        ),
      
      panel.grid.minor =
        element_blank(),
      
      legend.title =
        element_text(
          face = "bold"
        ),
      
      plot.margin =
        margin(
          8,
          8,
          8,
          8
        )
    )
}


# ==============================================================================
# 4. HELPERS
# ==============================================================================

clean_sample_id <- function(x) {
  
  x <- toupper(
    trimws(
      as.character(x)
    )
  )
  
  x <- gsub(
    "[^A-Z0-9]",
    "",
    x
  )
  
  return(x)
}


z_safe <- function(x) {
  
  x <- as.numeric(x)
  
  s <- stats::sd(
    x,
    na.rm = TRUE
  )
  
  if (
    !is.finite(s) ||
    s == 0
  ) {
    
    return(
      rep(
        NA_real_,
        length(x)
      )
    )
  }
  
  return(
    as.numeric(
      scale(x)
    )
  )
}


save_publication_plot <- function(
    plot_object,
    filename_stub,
    width,
    height
) {
  
  png_file <- file.path(
    figures_dir,
    paste0(
      filename_stub,
      ".png"
    )
  )
  
  pdf_file <- file.path(
    figures_dir,
    paste0(
      filename_stub,
      ".pdf"
    )
  )
  
  tiff_file <- file.path(
    figures_dir,
    paste0(
      filename_stub,
      ".tiff"
    )
  )
  
  
  ggsave(
    filename = png_file,
    plot = plot_object,
    width = width,
    height = height,
    dpi = 600
  )
  
  ggsave(
    filename = pdf_file,
    plot = plot_object,
    width = width,
    height = height
  )
  
  ggsave(
    filename = tiff_file,
    plot = plot_object,
    width = width,
    height = height,
    dpi = 600,
    compression = "lzw"
  )
  
  return(
    invisible(
      c(
        png_file,
        pdf_file,
        tiff_file
      )
    )
  )
}


# ==============================================================================
# 5. INPUT FILES
# ==============================================================================

scores135_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "135_validation",
  "tables",
  "135_blood_scores_with_final_endotypes.csv"
)

expression135_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "135_validation",
  "tables",
  "135_selected_gene_expression_logCPM.csv"
)

clinical136b_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "136b_demographic_sensitivity",
  "tables",
  "136b_BP_molecular_clinical_demographics.csv"
)

clinical_tests136b_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "136b_demographic_sensitivity",
  "tables",
  "136b_all_clinical_tests_updated_FDR.csv"
)

demographics136b_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "136b_demographic_sensitivity",
  "tables",
  "136b_blood_demographics.csv"
)

adjusted_genes136b_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "136b_demographic_sensitivity",
  "tables",
  "136b_primary_genes_age_sex_adjusted.csv"
)

benchmark_scores137_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "137_benchmarking",
  "tables",
  "137_all_blood_biomarker_scores.csv"
)

auc137_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "137_benchmarking",
  "tables",
  "137_BP_BC_AUC_benchmark.csv"
)

correlations137_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "137_benchmarking",
  "tables",
  "137_signature_correlations_primary_SRSq.csv"
)

endotypes137_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "137_benchmarking",
  "tables",
  "137_signature_endotype_associations.csv"
)

gene_audit137_file <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "137_benchmarking",
  "tables",
  "137_benchmark_gene_direction_audit.csv"
)


required_files <- c(
  scores135_file,
  expression135_file,
  clinical136b_file,
  clinical_tests136b_file,
  demographics136b_file,
  adjusted_genes136b_file,
  benchmark_scores137_file,
  auc137_file,
  correlations137_file,
  endotypes137_file,
  gene_audit137_file
)


if (any(!file.exists(required_files))) {
  
  missing_files <- required_files[
    !file.exists(
      required_files
    )
  ]
  
  stop(
    paste0(
      "Missing required input files:\n",
      paste(
        missing_files,
        collapse = "\n"
      )
    )
  )
}

cat("All required Script 135-137 outputs found.\n\n")


# ==============================================================================
# 6. OUTPUT DIRECTORIES
# ==============================================================================

output_dir <- file.path(
  "results",
  "blood_endotypes_biomarkers",
  "138_integrated_figures"
)

figures_dir <- file.path(
  output_dir,
  "figures"
)

tables_dir <- file.path(
  output_dir,
  "tables"
)

text_dir <- file.path(
  output_dir,
  "text"
)

logs_dir <- file.path(
  output_dir,
  "logs"
)


dir.create(
  figures_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  tables_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  text_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  logs_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


cat("Output folder:\n")

cat(
  normalizePath(
    output_dir,
    winslash = "/",
    mustWork = FALSE
  ),
  "\n\n"
)


# ==============================================================================
# 7. READ TABLES
# ==============================================================================

scores135 <- read.csv(
  scores135_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

expression135 <- read.csv(
  expression135_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

clinical136b <- read.csv(
  clinical136b_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

clinical_tests136b <- read.csv(
  clinical_tests136b_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

demographics136b <- read.csv(
  demographics136b_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

adjusted_genes136b <- read.csv(
  adjusted_genes136b_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

benchmark_scores137 <- read.csv(
  benchmark_scores137_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

auc137 <- read.csv(
  auc137_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

correlations137 <- read.csv(
  correlations137_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

endotypes137 <- read.csv(
  endotypes137_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

gene_audit137 <- read.csv(
  gene_audit137_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)


# ==============================================================================
# 8. CLEAN SAMPLE IDS
# ==============================================================================

scores135$sample_id <- clean_sample_id(
  scores135$sample_id
)

expression135$sample_id <- clean_sample_id(
  expression135$sample_id
)

clinical136b$sample_id <- clean_sample_id(
  clinical136b$sample_id
)

demographics136b$sample_id <- clean_sample_id(
  demographics136b$sample_id
)

benchmark_scores137$sample_id <- clean_sample_id(
  benchmark_scores137$sample_id
)


# ==============================================================================
# 9. VALIDATE BLOOD COHORT
# ==============================================================================

scores135$condition_plot <- dplyr::case_when(
  
  grepl(
    "^BP[0-9]+$",
    scores135$sample_id
  ) ~ "BP",
  
  grepl(
    "^BC[0-9]+$",
    scores135$sample_id
  ) ~ "BC",
  
  TRUE ~ NA_character_
)


scores135$condition_plot <- factor(
  scores135$condition_plot,
  levels = c(
    "BC",
    "BP"
  )
)


cat("Blood cohort:\n")

print(
  table(
    scores135$condition_plot
  )
)

cat("\n")


if (
  sum(
    scores135$condition_plot == "BP"
  ) != 35
) {
  
  stop(
    "Expected BP n=35."
  )
}


if (
  sum(
    scores135$condition_plot == "BC"
  ) != 10
) {
  
  stop(
    "Expected BC n=10."
  )
}


# ==============================================================================
# 10. PRIMARY GENE DEFINITIONS
# ==============================================================================

primary_up_genes <- c(
  "CD177",
  "HK3",
  "IRAK3"
)

primary_down_genes <- c(
  "CARD11",
  "IKZF2"
)

primary_genes <- c(
  primary_up_genes,
  primary_down_genes
)


missing_primary_genes <- setdiff(
  primary_genes,
  names(
    expression135
  )
)


if (length(missing_primary_genes) > 0) {
  
  stop(
    paste0(
      "Primary genes missing from expression table: ",
      paste(
        missing_primary_genes,
        collapse = ", "
      )
    )
  )
}


# ==============================================================================
# 11. FIGURE 1A
# FIVE-GENE SCORE: BP vs BC
# ==============================================================================

fig1a_data <- scores135 %>%
  filter(
    !is.na(
      primary_5gene_score
    ),
    !is.na(
      condition_plot
    )
  )


p1a <- ggplot(
  fig1a_data,
  aes(
    x = condition_plot,
    y = primary_5gene_score,
    fill = condition_plot
  )
) +
  
  geom_boxplot(
    width = 0.55,
    outlier.shape = NA,
    alpha = 0.60
  ) +
  
  geom_jitter(
    aes(
      color = condition_plot
    ),
    width = 0.10,
    size = 2.1,
    alpha = 0.90
  ) +
  
  scale_fill_manual(
    values = condition_colors
  ) +
  
  scale_color_manual(
    values = condition_colors
  ) +
  
  labs(
    title =
      "A  Five-gene host-response score",
    
    subtitle =
      "Sepsis versus healthy controls",
    
    x =
      NULL,
    
    y =
      "Myeloid-adaptive balance score"
  ) +
  
  theme_manuscript() +
  
  theme(
    legend.position = "none"
  )


# ==============================================================================
# 12. FIGURE 1B
# INDIVIDUAL FIVE-GENE EXPRESSION
# ==============================================================================

gene_long <- expression135 %>%
  
  select(
    sample_id,
    all_of(
      primary_genes
    )
  ) %>%
  
  left_join(
    scores135 %>%
      select(
        sample_id,
        condition_plot
      ),
    by = "sample_id"
  ) %>%
  
  pivot_longer(
    cols =
      all_of(
        primary_genes
      ),
    
    names_to =
      "gene",
    
    values_to =
      "logCPM"
  )


gene_long$gene <- factor(
  gene_long$gene,
  levels =
    primary_genes
)


p1b <- ggplot(
  gene_long,
  aes(
    x = condition_plot,
    y = logCPM,
    fill = condition_plot
  )
) +
  
  geom_boxplot(
    width = 0.58,
    outlier.shape = NA,
    alpha = 0.60
  ) +
  
  geom_jitter(
    aes(
      color = condition_plot
    ),
    width = 0.10,
    size = 1.3,
    alpha = 0.80
  ) +
  
  facet_wrap(
    ~ gene,
    scales = "free_y",
    nrow = 1
  ) +
  
  scale_fill_manual(
    values = condition_colors
  ) +
  
  scale_color_manual(
    values = condition_colors
  ) +
  
  labs(
    title =
      "B  Component-gene expression",
    
    x =
      NULL,
    
    y =
      "TMM logCPM"
  ) +
  
  theme_manuscript(
    base_size = 9
  ) +
  
  theme(
    legend.position = "none"
  )


# ==============================================================================
# 13. FIGURE 1C
# AGE/SEX-ADJUSTED COMPONENT-GENE EFFECTS
# ==============================================================================

adjusted_genes_plot <- adjusted_genes136b %>%
  mutate(
    
    direction =
      ifelse(
        adjusted_condition_logCPM_difference >= 0,
        "UP",
        "DOWN"
      ),
    
    gene =
      factor(
        gene,
        levels =
          rev(
            primary_genes
          )
      )
  )


p1c <- ggplot(
  adjusted_genes_plot,
  aes(
    x =
      adjusted_condition_logCPM_difference,
    
    y =
      gene,
    
    color =
      direction
  )
) +
  
  geom_vline(
    xintercept = 0,
    linetype = 2
  ) +
  
  geom_point(
    size = 3.2
  ) +
  
  scale_color_manual(
    values =
      gene_direction_colors
  ) +
  
  labs(
    title =
      "C  Age- and sex-adjusted effects",
    
    subtitle =
      "Adjusted BP minus BC logCPM difference",
    
    x =
      "Adjusted expression difference",
    
    y =
      NULL,
    
    color =
      "Direction"
  ) +
  
  theme_manuscript()


# ==============================================================================
# 14. COMPOSITE FIGURE 1
# ==============================================================================

figure1 <- (
  p1a |
    p1c
) /
  p1b +
  
  patchwork::plot_layout(
    heights = c(
      1,
      1.05
    )
  ) +
  
  patchwork::plot_annotation(
    
    title =
      "Blood five-gene host-response signature in sepsis",
    
    subtitle =
      paste0(
        "The composite score and all five component genes retain ",
        "the expected sepsis-associated direction."
      )
  )


save_publication_plot(
  plot_object =
    figure1,
  
  filename_stub =
    "138_Figure_1_five_gene_signature",
  
  width =
    12,
  
  height =
    9
)


# ==============================================================================
# 15. PREPARE BP ENDOTYPE DATA
# ==============================================================================

bp_data <- scores135 %>%
  filter(
    condition_plot == "BP"
  )


bp_data$SRS <- factor(
  bp_data$SRS,
  levels = c(
    "SRS1",
    "SRS2"
  )
)


bp_data$CTS <- factor(
  bp_data$CTS,
  levels = c(
    "CTS1",
    "CTS2",
    "CTS3"
  )
)


bp_data$CTS_SRS_state <- paste(
  bp_data$CTS,
  bp_data$SRS,
  sep = "/"
)


integrated_levels <- c(
  "CTS1/SRS1",
  "CTS2/SRS1",
  "CTS3/SRS1",
  "CTS3/SRS2"
)


bp_data$CTS_SRS_state <- factor(
  bp_data$CTS_SRS_state,
  levels =
    integrated_levels
)


# ==============================================================================
# 16. FIGURE 2A
# SCORE BY SRS
# ==============================================================================

p2a <- ggplot(
  bp_data,
  aes(
    x = SRS,
    y = primary_5gene_score,
    fill = SRS
  )
) +
  
  geom_boxplot(
    width = 0.58,
    outlier.shape = NA,
    alpha = 0.65
  ) +
  
  geom_jitter(
    aes(
      color = SRS
    ),
    width = 0.10,
    size = 2.0
  ) +
  
  scale_fill_manual(
    values = srs_colors
  ) +
  
  scale_color_manual(
    values = srs_colors
  ) +
  
  labs(
    title =
      "A  Five-gene score by SRS",
    
    subtitle =
      "Wilcoxon p = 3.61e-4",
    
    x =
      NULL,
    
    y =
      "Five-gene score"
  ) +
  
  theme_manuscript() +
  
  theme(
    legend.position = "none"
  )


# ==============================================================================
# 17. FIGURE 2B
# SCORE BY CTS
# ==============================================================================

p2b <- ggplot(
  bp_data,
  aes(
    x = CTS,
    y = primary_5gene_score,
    fill = CTS
  )
) +
  
  geom_boxplot(
    width = 0.58,
    outlier.shape = NA,
    alpha = 0.65
  ) +
  
  geom_jitter(
    aes(
      color = CTS
    ),
    width = 0.10,
    size = 2.0
  ) +
  
  scale_fill_manual(
    values = cts_colors
  ) +
  
  scale_color_manual(
    values = cts_colors
  ) +
  
  labs(
    title =
      "B  Five-gene score across CTS",
    
    subtitle =
      "Kruskal-Wallis p = 9.44e-6; epsilon^2 = 0.661",
    
    x =
      NULL,
    
    y =
      "Five-gene score"
  ) +
  
  theme_manuscript() +
  
  theme(
    legend.position = "none"
  )


# ==============================================================================
# 18. FIGURE 2C
# INTEGRATED CTS/SRS STATES
# ==============================================================================

p2c <- ggplot(
  bp_data %>%
    filter(
      !is.na(
        CTS_SRS_state
      )
    ),
  aes(
    x = CTS_SRS_state,
    y = primary_5gene_score,
    fill = CTS_SRS_state
  )
) +
  
  geom_boxplot(
    width = 0.58,
    outlier.shape = NA,
    alpha = 0.68
  ) +
  
  geom_jitter(
    aes(
      color =
        CTS_SRS_state
    ),
    width = 0.10,
    size = 1.9
  ) +
  
  scale_fill_manual(
    values =
      integrated_colors
  ) +
  
  scale_color_manual(
    values =
      integrated_colors
  ) +
  
  labs(
    title =
      "C  Integrated CTS/SRS states",
    
    subtitle =
      "Kruskal-Wallis p = 1.91e-5; epsilon^2 = 0.695",
    
    x =
      NULL,
    
    y =
      "Five-gene score"
  ) +
  
  theme_manuscript(
    base_size = 10
  ) +
  
  theme(
    legend.position = "none",
    axis.text.x =
      element_text(
        angle = 25,
        hjust = 1
      )
  )


# ==============================================================================
# 19. FIGURE 2D
# SCORE vs SRSq
# ==============================================================================

p2d <- ggplot(
  bp_data,
  aes(
    x = SRSq,
    y = primary_5gene_score,
    color = CTS,
    shape = SRS
  )
) +
  
  geom_point(
    size = 3.0,
    alpha = 0.9
  ) +
  
  geom_smooth(
    method = "lm",
    formula = y ~ x,
    se = TRUE,
    inherit.aes = FALSE,
    aes(
      x = SRSq,
      y = primary_5gene_score
    ),
    color = "#555555",
    fill = "#D9D9D9",
    linewidth = 0.7
  ) +
  
  scale_color_manual(
    values = cts_colors
  ) +
  
  scale_shape_manual(
    values = c(
      "SRS1" = 16,
      "SRS2" = 17
    )
  ) +
  
  labs(
    title =
      "D  Continuous SRS alignment",
    
    subtitle =
      "Spearman rho = 0.765; p = 8.74e-8",
    
    x =
      "SRSq",
    
    y =
      "Five-gene score",
    
    color =
      "CTS",
    
    shape =
      "SRS"
  ) +
  
  theme_manuscript()


# ==============================================================================
# 20. COMPOSITE FIGURE 2
# ==============================================================================

figure2 <- (
  p2a |
    p2b
) /
  (
    p2c |
      p2d
  ) +
  
  patchwork::plot_annotation(
    
    title =
      "Hierarchical organization of blood transcriptomic endotypes",
    
    subtitle =
      paste0(
        "The five-gene score captures categorical SRS/CTS states ",
        "and the continuous host-response axis."
      )
  )


save_publication_plot(
  plot_object =
    figure2,
  
  filename_stub =
    "138_Figure_2_endotype_hierarchy",
  
  width =
    13,
  
  height =
    10
)


# ==============================================================================
# 21. FIGURE 3
# FIVE-GENE ENDOTYPE HEATMAP
#
# IMPORTANT FIX:
# Expression table is reduced to sample_id + five genes BEFORE joining
# SRS/CTS metadata. This prevents CTS.x / CTS.y and SRS.x / SRS.y conflicts.
# ==============================================================================

heatmap_expression <- expression135 %>%
  
  select(
    sample_id,
    all_of(
      primary_genes
    )
  ) %>%
  
  filter(
    grepl(
      "^BP[0-9]+$",
      sample_id
    )
  )


heatmap_endotypes <- bp_data %>%
  
  select(
    sample_id,
    SRS,
    SRSq,
    CTS
  )


heatmap_data <- heatmap_expression %>%
  
  left_join(
    heatmap_endotypes,
    by = "sample_id"
  )


if (
  !"CTS" %in%
  names(
    heatmap_data
  )
) {
  
  stop(
    paste0(
      "CTS column not available after heatmap merge. Columns are:\n",
      paste(
        names(
          heatmap_data
        ),
        collapse = ", "
      )
    )
  )
}


if (
  !"SRS" %in%
  names(
    heatmap_data
  )
) {
  
  stop(
    "SRS column not available after heatmap merge."
  )
}


if (
  nrow(
    heatmap_data
  ) != 35
) {
  
  stop(
    paste0(
      "Expected 35 BP rows for heatmap; observed ",
      nrow(
        heatmap_data
      )
    )
  )
}


heatmap_data <- heatmap_data %>%
  
  arrange(
    CTS,
    SRS,
    desc(
      SRSq
    )
  )


cat("Heatmap endotype distribution:\n")

print(
  table(
    heatmap_data$CTS,
    heatmap_data$SRS
  )
)

cat("\n")


heatmap_samples <- heatmap_data$sample_id


heatmap_matrix_samples_by_gene <- as.matrix(
  heatmap_data[
    ,
    primary_genes,
    drop = FALSE
  ]
)


storage.mode(
  heatmap_matrix_samples_by_gene
) <- "numeric"


rownames(
  heatmap_matrix_samples_by_gene
) <- heatmap_samples


# Standardize each gene across the 35 BP samples

heatmap_z_samples_by_gene <- scale(
  heatmap_matrix_samples_by_gene
)


heatmap_matrix <- t(
  heatmap_z_samples_by_gene
)


colnames(
  heatmap_matrix
) <- heatmap_samples


heatmap_annotation <- data.frame(
  
  CTS =
    factor(
      heatmap_data$CTS,
      levels = c(
        "CTS1",
        "CTS2",
        "CTS3"
      )
    ),
  
  SRS =
    factor(
      heatmap_data$SRS,
      levels = c(
        "SRS1",
        "SRS2"
      )
    )
)


rownames(
  heatmap_annotation
) <- heatmap_samples


annotation_colors <- list(
  CTS = cts_colors,
  SRS = srs_colors
)


heatmap_colors <- colorRampPalette(
  c(
    "#2166AC",
    "#F7F7F7",
    "#B2182B"
  )
)(
  101
)


heatmap_breaks <- seq(
  -2.5,
  2.5,
  length.out = 102
)


heatmap_png <- file.path(
  figures_dir,
  "138_Figure_3_five_gene_endotype_heatmap.png"
)


heatmap_pdf <- file.path(
  figures_dir,
  "138_Figure_3_five_gene_endotype_heatmap.pdf"
)


heatmap_tiff <- file.path(
  figures_dir,
  "138_Figure_3_five_gene_endotype_heatmap.tiff"
)


pheatmap::pheatmap(
  
  heatmap_matrix,
  
  cluster_rows =
    FALSE,
  
  cluster_cols =
    FALSE,
  
  annotation_col =
    heatmap_annotation,
  
  annotation_colors =
    annotation_colors,
  
  color =
    heatmap_colors,
  
  breaks =
    heatmap_breaks,
  
  fontsize =
    9,
  
  fontsize_row =
    11,
  
  fontsize_col =
    6,
  
  border_color =
    NA,
  
  angle_col =
    90,
  
  main =
    "Five-gene expression architecture across sepsis endotypes",
  
  filename =
    heatmap_png,
  
  width =
    11,
  
  height =
    5
)


pheatmap::pheatmap(
  
  heatmap_matrix,
  
  cluster_rows =
    FALSE,
  
  cluster_cols =
    FALSE,
  
  annotation_col =
    heatmap_annotation,
  
  annotation_colors =
    annotation_colors,
  
  color =
    heatmap_colors,
  
  breaks =
    heatmap_breaks,
  
  fontsize =
    9,
  
  fontsize_row =
    11,
  
  fontsize_col =
    6,
  
  border_color =
    NA,
  
  angle_col =
    90,
  
  main =
    "Five-gene expression architecture across sepsis endotypes",
  
  filename =
    heatmap_pdf,
  
  width =
    11,
  
  height =
    5
)


tiff(
  filename =
    heatmap_tiff,
  
  width =
    11,
  
  height =
    5,
  
  units =
    "in",
  
  res =
    600,
  
  compression =
    "lzw"
)


pheatmap::pheatmap(
  
  heatmap_matrix,
  
  cluster_rows =
    FALSE,
  
  cluster_cols =
    FALSE,
  
  annotation_col =
    heatmap_annotation,
  
  annotation_colors =
    annotation_colors,
  
  color =
    heatmap_colors,
  
  breaks =
    heatmap_breaks,
  
  fontsize =
    9,
  
  fontsize_row =
    11,
  
  fontsize_col =
    6,
  
  border_color =
    NA,
  
  angle_col =
    90,
  
  main =
    "Five-gene expression architecture across sepsis endotypes"
)


dev.off()


# ==============================================================================
# 22. PREPARE CLINICAL BP DATA
# ==============================================================================

clinical_bp <- clinical136b %>%
  
  filter(
    grepl(
      "^BP[0-9]+$",
      sample_id
    )
  )


if (nrow(clinical_bp) != 35) {
  
  stop(
    paste0(
      "Expected 35 BP clinical rows; observed ",
      nrow(
        clinical_bp
      )
    )
  )
}


# ==============================================================================
# 23. FIGURE 4A
# PRIMARY SCORE vs CRP
# ==============================================================================

required_clinical_plot_columns <- c(
  "primary_5gene_score",
  "crp_numeric",
  "CTS"
)


missing_clinical_plot_columns <- setdiff(
  required_clinical_plot_columns,
  names(
    clinical_bp
  )
)


if (length(missing_clinical_plot_columns) > 0) {
  
  stop(
    paste0(
      "Missing clinical plotting columns: ",
      paste(
        missing_clinical_plot_columns,
        collapse = ", "
      )
    )
  )
}


clinical_bp$CTS <- factor(
  clinical_bp$CTS,
  levels = c(
    "CTS1",
    "CTS2",
    "CTS3"
  )
)


p4a <- ggplot(
  clinical_bp %>%
    filter(
      !is.na(
        crp_numeric
      ),
      !is.na(
        primary_5gene_score
      )
    ),
  aes(
    x = crp_numeric,
    y = primary_5gene_score,
    color = CTS
  )
) +
  
  geom_point(
    size = 2.8,
    alpha = 0.90
  ) +
  
  geom_smooth(
    method = "lm",
    formula = y ~ x,
    se = TRUE,
    inherit.aes = FALSE,
    aes(
      x = crp_numeric,
      y = primary_5gene_score
    ),
    color = "#555555",
    fill = "#D9D9D9",
    linewidth = 0.7
  ) +
  
  scale_color_manual(
    values = cts_colors
  ) +
  
  labs(
    title =
      "A  Association with systemic inflammation",
    
    subtitle =
      "CRP: Spearman rho = 0.574; p = 3.09e-4; global BH = 0.0185",
    
    x =
      "CRP, mg/L",
    
    y =
      "Five-gene score",
    
    color =
      "CTS"
  ) +
  
  theme_manuscript()


# ==============================================================================
# 24. FIGURE 4B
# CONTINUOUS CLINICAL CORRELATIONS
# ==============================================================================

clinical_corr_plot_data <- clinical_tests136b %>%
  
  filter(
    test == "Spearman",
    
    framework %in%
      c(
        "Primary_5gene_score",
        "SRSq"
      ),
    
    !is.na(
      effect
    )
  ) %>%
  
  mutate(
    
    framework_label =
      dplyr::recode(
        framework,
        
        "Primary_5gene_score" =
          "Five-gene score",
        
        "SRSq" =
          "SRSq"
      ),
    
    significance =
      case_when(
        
        !is.na(
          BH_global
        ) &
          BH_global < 0.05 ~
          "FDR < 0.05",
        
        !is.na(
          p_value
        ) &
          p_value < 0.05 ~
          "Nominal p < 0.05",
        
        TRUE ~
          "NS"
      )
  )


p4b <- ggplot(
  clinical_corr_plot_data,
  aes(
    x = effect,
    y = reorder(
      clinical_label,
      effect
    ),
    color = significance
  )
) +
  
  geom_vline(
    xintercept = 0,
    linetype = 2
  ) +
  
  geom_point(
    size = 3
  ) +
  
  facet_wrap(
    ~ framework_label
  ) +
  
  scale_color_manual(
    values =
      significance_colors
  ) +
  
  labs(
    title =
      "B  Continuous clinical correlates",
    
    x =
      "Spearman rho",
    
    y =
      NULL,
    
    color =
      "Statistical support"
  ) +
  
  theme_manuscript(
    base_size = 9
  )


# ==============================================================================
# 25. COMPOSITE FIGURE 4
# ==============================================================================

figure4 <- (
  p4a |
    p4b
) +
  
  patchwork::plot_layout(
    widths = c(
      1,
      1.35
    )
  ) +
  
  patchwork::plot_annotation(
    
    title =
      "Clinical context of the blood host-response axis",
    
    subtitle =
      paste0(
        "CRP is the only continuous clinical variable associated ",
        "with both the five-gene score and SRSq after global FDR correction."
      )
  )


save_publication_plot(
  plot_object =
    figure4,
  
  filename_stub =
    "138_Figure_4_clinical_context",
  
  width =
    13,
  
  height =
    6
)


# ==============================================================================
# 26. PREPARE SIGNATURE ORDER
# ==============================================================================

signature_order <- c(
  "Primary 5-gene",
  "LIFTS-like",
  "DCAF17 alternative",
  "FAIM3:PLAC8-like",
  "Sepsis MetaScore-like",
  "PLAC8-PLA2G7 contrast",
  "SeptiCyte LAB-like"
)


correlations137$display_name <- factor(
  correlations137$display_name,
  levels =
    rev(
      signature_order
    )
)


endotypes137$display_name <- factor(
  endotypes137$display_name,
  levels =
    rev(
      signature_order
    )
)


# ==============================================================================
# 27. FIGURE 5A
# EXTERNAL SIGNATURES vs PRIMARY
# ==============================================================================

corr_primary <- correlations137 %>%
  
  filter(
    target ==
      "primary_5gene_score",
    
    as.character(
      display_name
    ) !=
      "Primary 5-gene"
  )


p5a <- ggplot(
  corr_primary,
  aes(
    x = Spearman_rho,
    y = display_name,
    color = display_name
  )
) +
  
  geom_vline(
    xintercept = 0,
    linetype = 2
  ) +
  
  geom_segment(
    aes(
      x = 0,
      xend = Spearman_rho,
      yend = display_name
    ),
    linewidth = 0.7
  ) +
  
  geom_point(
    size = 3.4
  ) +
  
  scale_color_manual(
    values =
      signature_colors
  ) +
  
  coord_cartesian(
    xlim = c(
      0,
      1
    )
  ) +
  
  labs(
    title =
      "A  Published signatures align with the five-gene score",
    
    x =
      "Spearman rho with primary five-gene score",
    
    y =
      NULL
  ) +
  
  theme_manuscript(
    base_size = 9
  ) +
  
  theme(
    legend.position = "none"
  )


# ==============================================================================
# 28. FIGURE 5B
# SIGNATURES vs SRSq
# ==============================================================================

corr_srsq <- correlations137 %>%
  
  filter(
    target ==
      "SRSq"
  )


p5b <- ggplot(
  corr_srsq,
  aes(
    x = Spearman_rho,
    y = display_name,
    color = display_name
  )
) +
  
  geom_vline(
    xintercept = 0,
    linetype = 2
  ) +
  
  geom_segment(
    aes(
      x = 0,
      xend = Spearman_rho,
      yend = display_name
    ),
    linewidth = 0.7
  ) +
  
  geom_point(
    size = 3.4
  ) +
  
  scale_color_manual(
    values =
      signature_colors
  ) +
  
  coord_cartesian(
    xlim = c(
      0,
      1
    )
  ) +
  
  labs(
    title =
      "B  Signatures converge on the SRS axis",
    
    x =
      "Spearman rho with SRSq",
    
    y =
      NULL
  ) +
  
  theme_manuscript(
    base_size = 9
  ) +
  
  theme(
    legend.position = "none"
  )


# ==============================================================================
# 29. FIGURE 5C
# CTS EFFECT SIZE
# ==============================================================================

cts_effects <- endotypes137 %>%
  
  filter(
    framework ==
      "CTS"
  )


p5c <- ggplot(
  cts_effects,
  aes(
    x = effect,
    y = display_name,
    color = display_name
  )
) +
  
  geom_segment(
    aes(
      x = 0,
      xend = effect,
      yend = display_name
    ),
    linewidth = 0.7
  ) +
  
  geom_point(
    size = 3.4
  ) +
  
  scale_color_manual(
    values =
      signature_colors
  ) +
  
  coord_cartesian(
    xlim = c(
      0,
      0.75
    )
  ) +
  
  labs(
    title =
      "C  CTS effect size across signatures",
    
    subtitle =
      "All evaluated signatures remain significant after BH correction",
    
    x =
      "Kruskal-Wallis epsilon^2",
    
    y =
      NULL
  ) +
  
  theme_manuscript(
    base_size = 9
  ) +
  
  theme(
    legend.position = "none"
  )


# ==============================================================================
# 30. FIGURE 5D
# SELECTED SIGNATURE TRAJECTORIES
# ==============================================================================

selected_signature_columns <- c(
  "primary_5gene_score",
  "LIFTS_like",
  "FAIM3_PLAC8_like",
  "Sepsis_MetaScore_like"
)


selected_signature_names <- c(
  "primary_5gene_score" = "Primary 5-gene",
  "LIFTS_like" = "LIFTS-like",
  "FAIM3_PLAC8_like" = "FAIM3:PLAC8-like",
  "Sepsis_MetaScore_like" = "Sepsis MetaScore-like"
)


trajectory_data <- benchmark_scores137 %>%
  
  filter(
    grepl(
      "^BP[0-9]+$",
      sample_id
    )
  ) %>%
  
  select(
    sample_id,
    CTS,
    all_of(
      selected_signature_columns
    )
  ) %>%
  
  pivot_longer(
    cols =
      all_of(
        selected_signature_columns
      ),
    
    names_to =
      "score_column",
    
    values_to =
      "score"
  ) %>%
  
  group_by(
    score_column
  ) %>%
  
  mutate(
    score_z =
      z_safe(
        score
      )
  ) %>%
  
  ungroup() %>%
  
  mutate(
    
    display_name =
      unname(
        selected_signature_names[
          score_column
        ]
      ),
    
    CTS =
      factor(
        CTS,
        levels = c(
          "CTS1",
          "CTS2",
          "CTS3"
        )
      )
  )


trajectory_summary <- trajectory_data %>%
  
  group_by(
    display_name,
    CTS
  ) %>%
  
  summarise(
    
    median_score =
      median(
        score_z,
        na.rm = TRUE
      ),
    
    q1 =
      quantile(
        score_z,
        0.25,
        na.rm = TRUE
      ),
    
    q3 =
      quantile(
        score_z,
        0.75,
        na.rm = TRUE
      ),
    
    .groups =
      "drop"
  )


p5d <- ggplot(
  trajectory_summary,
  aes(
    x = CTS,
    y = median_score,
    group = display_name,
    color = display_name
  )
) +
  
  geom_line(
    linewidth = 1.0
  ) +
  
  geom_point(
    size = 3
  ) +
  
  geom_errorbar(
    aes(
      ymin = q1,
      ymax = q3
    ),
    width = 0.08,
    linewidth = 0.6
  ) +
  
  scale_color_manual(
    values =
      signature_colors
  ) +
  
  labs(
    title =
      "D  Convergent CTS trajectories",
    
    subtitle =
      "Median standardized score with interquartile range",
    
    x =
      "Consensus Transcriptomic Subtype",
    
    y =
      "Standardized signature score",
    
    color =
      "Signature"
  ) +
  
  theme_manuscript(
    base_size = 9
  ) +
  
  theme(
    legend.position = "bottom"
  )


# ==============================================================================
# 31. COMPOSITE FIGURE 5
# ==============================================================================

figure5 <- (
  p5a |
    p5b
) /
  (
    p5c |
      p5d
  ) +
  
  patchwork::plot_annotation(
    
    title =
      "Blood transcriptomic signatures converge on a common host-response continuum",
    
    subtitle =
      paste0(
        "Published sepsis-associated signatures align with the primary ",
        "five-gene score, SRSq and CTS organization."
      )
  )


save_publication_plot(
  plot_object =
    figure5,
  
  filename_stub =
    "138_Figure_5_cross_signature_convergence",
  
  width =
    14,
  
  height =
    10
)


# ==============================================================================
# 32. SUPPLEMENTARY FIGURE S1
# DEMOGRAPHIC SENSITIVITY
# ==============================================================================

demographics136b$condition <- factor(
  demographics136b$condition,
  levels = c(
    "BC",
    "BP"
  )
)


s1a <- ggplot(
  demographics136b,
  aes(
    x = condition,
    y = age_years,
    fill = condition
  )
) +
  
  geom_boxplot(
    outlier.shape = NA,
    alpha = 0.60
  ) +
  
  geom_jitter(
    aes(
      color = condition
    ),
    width = 0.10,
    size = 1.8
  ) +
  
  scale_fill_manual(
    values = condition_colors
  ) +
  
  scale_color_manual(
    values = condition_colors
  ) +
  
  labs(
    title =
      "A  Age",
    
    subtitle =
      "BP vs BC: Wilcoxon p = 0.00743",
    
    x =
      NULL,
    
    y =
      "Age, years"
  ) +
  
  theme_manuscript() +
  
  theme(
    legend.position = "none"
  )


bp_demo_plot <- clinical136b %>%
  filter(
    !is.na(
      age_years
    )
  )


s1b <- ggplot(
  bp_demo_plot,
  aes(
    x = age_years,
    y = primary_5gene_score,
    color = CTS
  )
) +
  
  geom_point(
    size = 2.3
  ) +
  
  geom_smooth(
    method = "lm",
    formula = y ~ x,
    se = TRUE,
    color = "#555555",
    fill = "#D9D9D9"
  ) +
  
  scale_color_manual(
    values = cts_colors
  ) +
  
  labs(
    title =
      "B  Five-gene score versus age",
    
    subtitle =
      "Spearman rho = -0.108; p = 0.542",
    
    x =
      "Age, years",
    
    y =
      "Five-gene score",
    
    color =
      "CTS"
  ) +
  
  theme_manuscript()


s1c <- ggplot(
  clinical136b,
  aes(
    x = sex,
    y = primary_5gene_score,
    fill = sex
  )
) +
  
  geom_boxplot(
    outlier.shape = NA,
    alpha = 0.60
  ) +
  
  geom_jitter(
    width = 0.10,
    size = 1.8
  ) +
  
  scale_fill_manual(
    values = c(
      "Female" = "#CC79A7",
      "Male" = "#0072B2"
    )
  ) +
  
  labs(
    title =
      "C  Five-gene score by sex",
    
    subtitle =
      "Wilcoxon p = 0.709",
    
    x =
      NULL,
    
    y =
      "Five-gene score"
  ) +
  
  theme_manuscript() +
  
  theme(
    legend.position = "none"
  )


figure_s1 <- (
  s1a |
    s1b |
    s1c
) +
  
  patchwork::plot_annotation(
    
    title =
      "Supplementary Figure S1. Demographic sensitivity analyses",
    
    subtitle =
      paste0(
        "Although BP and BC differ in age and sex distribution, ",
        "the five-gene host-response axis is not associated ",
        "with either variable within sepsis."
      )
  )


save_publication_plot(
  plot_object =
    figure_s1,
  
  filename_stub =
    "138_Supplementary_Figure_S1_demographics",
  
  width =
    15,
  
  height =
    5.5
)


# ==============================================================================
# 33. SUPPLEMENTARY FIGURE S2
# CONTEXTUAL AUC BENCHMARKING
# ==============================================================================

auc_plot <- auc137 %>%
  
  mutate(
    display_name =
      factor(
        display_name,
        levels =
          rev(
            signature_order
          )
      )
  )


figure_s2 <- ggplot(
  auc_plot,
  aes(
    x = AUC_fixed_direction,
    y = display_name,
    color = display_name
  )
) +
  
  geom_errorbar(
    aes(
      xmin = AUC_CI_low,
      xmax = AUC_CI_high
    ),
    width = 0.15,
    orientation = "y"
  ) +
  
  geom_point(
    size = 3.5
  ) +
  
  geom_vline(
    xintercept = 0.5,
    linetype = 2
  ) +
  
  scale_color_manual(
    values =
      signature_colors
  ) +
  
  coord_cartesian(
    xlim = c(
      0.45,
      1.02
    )
  ) +
  
  labs(
    title =
      "Supplementary Figure S2. Contextual BP-versus-BC biomarker benchmarking",
    
    subtitle =
      paste0(
        "Sepsis versus healthy controls; apparent AUC only. ",
        "This is not independent diagnostic validation."
      ),
    
    x =
      "AUC",
    
    y =
      NULL
  ) +
  
  theme_manuscript() +
  
  theme(
    legend.position = "none"
  )


save_publication_plot(
  plot_object =
    figure_s2,
  
  filename_stub =
    "138_Supplementary_Figure_S2_AUC_benchmark",
  
  width =
    9,
  
  height =
    6
)


# ==============================================================================
# 34. SUPPLEMENTARY FIGURE S3
# BIOMARKER-GENE DIRECTION AUDIT
# ==============================================================================

gene_audit_plot <- gene_audit137 %>%
  
  filter(
    present,
    !is.na(
      BP_minus_BC
    )
  ) %>%
  
  mutate(
    
    observed_direction =
      factor(
        observed_direction,
        levels = c(
          "DOWN",
          "UP"
        )
      ),
    
    canonical_gene =
      reorder(
        canonical_gene,
        BP_minus_BC
      )
  )


figure_s3 <- ggplot(
  gene_audit_plot,
  aes(
    x = BP_minus_BC,
    y = canonical_gene,
    color = observed_direction
  )
) +
  
  geom_vline(
    xintercept = 0,
    linetype = 2
  ) +
  
  geom_segment(
    aes(
      x = 0,
      xend = BP_minus_BC,
      yend = canonical_gene
    ),
    linewidth = 0.55,
    alpha = 0.75
  ) +
  
  geom_point(
    size = 3
  ) +
  
  scale_color_manual(
    values =
      gene_direction_colors
  ) +
  
  labs(
    title =
      "Supplementary Figure S3. Direction audit of predefined biomarker genes",
    
    subtitle =
      "Median TMM logCPM difference: sepsis minus healthy controls",
    
    x =
      "Median BP - BC logCPM",
    
    y =
      NULL,
    
    color =
      "Observed direction"
  ) +
  
  theme_manuscript(
    base_size = 9
  )


save_publication_plot(
  plot_object =
    figure_s3,
  
  filename_stub =
    "138_Supplementary_Figure_S3_gene_direction_audit",
  
  width =
    9,
  
  height =
    10
)


# ==============================================================================
# 35. SUPPLEMENTARY FIGURE S4
# ALL SIGNATURES ACROSS CTS
# ==============================================================================

all_signature_columns <- c(
  "primary_5gene_score",
  "DCAF17_alt_score",
  "SeptiCyte_LAB_like",
  "SeptiCyte_RAPID_like",
  "FAIM3_PLAC8_like",
  "Sepsis_MetaScore_like",
  "LIFTS_like"
)


all_signature_names <- c(
  "primary_5gene_score" = "Primary 5-gene",
  "DCAF17_alt_score" = "DCAF17 alternative",
  "SeptiCyte_LAB_like" = "SeptiCyte LAB-like",
  "SeptiCyte_RAPID_like" = "PLAC8-PLA2G7 contrast",
  "FAIM3_PLAC8_like" = "FAIM3:PLAC8-like",
  "Sepsis_MetaScore_like" = "Sepsis MetaScore-like",
  "LIFTS_like" = "LIFTS-like"
)


s4_data <- benchmark_scores137 %>%
  
  filter(
    grepl(
      "^BP[0-9]+$",
      sample_id
    )
  ) %>%
  
  select(
    sample_id,
    CTS,
    all_of(
      all_signature_columns
    )
  ) %>%
  
  pivot_longer(
    cols =
      all_of(
        all_signature_columns
      ),
    
    names_to =
      "score_column",
    
    values_to =
      "score"
  ) %>%
  
  group_by(
    score_column
  ) %>%
  
  mutate(
    score_z =
      z_safe(
        score
      )
  ) %>%
  
  ungroup() %>%
  
  mutate(
    
    display_name =
      unname(
        all_signature_names[
          score_column
        ]
      ),
    
    CTS =
      factor(
        CTS,
        levels = c(
          "CTS1",
          "CTS2",
          "CTS3"
        )
      )
  )


figure_s4 <- ggplot(
  s4_data,
  aes(
    x = CTS,
    y = score_z,
    fill = CTS
  )
) +
  
  geom_boxplot(
    outlier.shape = NA,
    alpha = 0.65
  ) +
  
  geom_jitter(
    aes(
      color = CTS
    ),
    width = 0.10,
    size = 1.2
  ) +
  
  facet_wrap(
    ~ display_name,
    ncol = 3
  ) +
  
  scale_fill_manual(
    values =
      cts_colors
  ) +
  
  scale_color_manual(
    values =
      cts_colors
  ) +
  
  labs(
    title =
      "Supplementary Figure S4. Blood biomarker signatures across CTS classes",
    
    subtitle =
      "Scores standardized within the sepsis cohort",
    
    x =
      "Consensus Transcriptomic Subtype",
    
    y =
      "Standardized score"
  ) +
  
  theme_manuscript(
    base_size = 8
  ) +
  
  theme(
    legend.position = "none"
  )


save_publication_plot(
  plot_object =
    figure_s4,
  
  filename_stub =
    "138_Supplementary_Figure_S4_all_signatures_CTS",
  
  width =
    12,
  
  height =
    9
)


# ==============================================================================
# 36. FIGURE MANIFEST
# ==============================================================================

figure_manifest <- tibble(
  
  figure = c(
    "Figure 1",
    "Figure 2",
    "Figure 3",
    "Figure 4",
    "Figure 5",
    "Supplementary Figure S1",
    "Supplementary Figure S2",
    "Supplementary Figure S3",
    "Supplementary Figure S4"
  ),
  
  filename_stub = c(
    "138_Figure_1_five_gene_signature",
    "138_Figure_2_endotype_hierarchy",
    "138_Figure_3_five_gene_endotype_heatmap",
    "138_Figure_4_clinical_context",
    "138_Figure_5_cross_signature_convergence",
    "138_Supplementary_Figure_S1_demographics",
    "138_Supplementary_Figure_S2_AUC_benchmark",
    "138_Supplementary_Figure_S3_gene_direction_audit",
    "138_Supplementary_Figure_S4_all_signatures_CTS"
  ),
  
  manuscript_role = c(
    
    "Primary five-gene blood host-response signature",
    
    "Hierarchical SRS/CTS organization and host-response axis",
    
    "Five-gene expression architecture across blood endotypes",
    
    "Clinical context with emphasis on CRP",
    
    "Cross-signature convergence",
    
    "Demographic sensitivity",
    
    "Contextual AUC benchmarking",
    
    "Predefined biomarker-gene direction audit",
    
    "Complete signature distributions across CTS"
  )
)


write.csv(
  figure_manifest,
  file.path(
    tables_dir,
    "138_figure_manifest.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 37. COLOR PALETTE MANIFEST
# ==============================================================================

palette_manifest <- bind_rows(
  
  tibble(
    category = "Condition",
    level = names(
      condition_colors
    ),
    color = unname(
      condition_colors
    )
  ),
  
  tibble(
    category = "SRS",
    level = names(
      srs_colors
    ),
    color = unname(
      srs_colors
    )
  ),
  
  tibble(
    category = "CTS",
    level = names(
      cts_colors
    ),
    color = unname(
      cts_colors
    )
  ),
  
  tibble(
    category = "Integrated CTS/SRS",
    level = names(
      integrated_colors
    ),
    color = unname(
      integrated_colors
    )
  ),
  
  tibble(
    category = "Signature",
    level = names(
      signature_colors
    ),
    color = unname(
      signature_colors
    )
  )
)


write.csv(
  palette_manifest,
  file.path(
    tables_dir,
    "138_publication_color_palette.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 38. FIGURE NOTES
# ==============================================================================

figure_notes <- c(
  
  "SCRIPT 138 - INTEGRATED PUBLICATION FIGURES",
  
  "====================================================================",
  
  "",
  
  "No new feature selection or biomarker discovery was performed.",
  
  paste0(
    "Figures were generated from validated outputs of Scripts ",
    "135, 136b and 137."
  ),
  
  "",
  
  "COLOR SYSTEM:",
  
  "BC: cyan-blue",
  
  "BP: red-orange",
  
  "SRS1: orange-red",
  
  "SRS2: blue",
  
  "CTS1: amber",
  
  "CTS2: light blue",
  
  "CTS3: green",
  
  "",
  
  "MAIN FIGURE INTERPRETATION:",
  
  paste0(
    "Figure 1 demonstrates the compact five-gene blood ",
    "host-response signature."
  ),
  
  paste0(
    "Figure 2 demonstrates hierarchical SRS/CTS organization ",
    "and the continuous host-response axis."
  ),
  
  paste0(
    "Figure 3 displays the component-gene architecture across ",
    "ordered sepsis endotypes."
  ),
  
  paste0(
    "Figure 4 provides exploratory clinical context; CRP is the ",
    "only continuous clinical correlate surviving global FDR ",
    "for both the five-gene score and SRSq."
  ),
  
  paste0(
    "Figure 5 demonstrates convergence of independently published ",
    "blood transcriptomic signatures on the same host-response continuum."
  ),
  
  "",
  
  "IMPORTANT:",
  
  paste0(
    "Contextual BP-vs-BC AUC analyses are retained in Supplementary ",
    "material because controls are healthy volunteers and the primary ",
    "five-gene panel was selected in the same cohort."
  )
)


writeLines(
  figure_notes,
  file.path(
    text_dir,
    "138_figure_notes.txt"
  )
)


# ==============================================================================
# 39. INPUT MANIFEST
# ==============================================================================

input_manifest <- tibble(
  
  input = c(
    "Script135_scores",
    "Script135_expression",
    "Script136b_clinical",
    "Script136b_clinical_tests",
    "Script136b_demographics",
    "Script136b_adjusted_genes",
    "Script137_scores",
    "Script137_AUC",
    "Script137_correlations",
    "Script137_endotypes",
    "Script137_gene_audit"
  ),
  
  path = c(
    scores135_file,
    expression135_file,
    clinical136b_file,
    clinical_tests136b_file,
    demographics136b_file,
    adjusted_genes136b_file,
    benchmark_scores137_file,
    auc137_file,
    correlations137_file,
    endotypes137_file,
    gene_audit137_file
  )
)


file_information <- file.info(
  input_manifest$path
)


input_manifest$file_size_bytes <-
  file_information$size


input_manifest$modified_time <-
  as.character(
    file_information$mtime
  )


input_manifest$md5 <-
  unname(
    tools::md5sum(
      input_manifest$path
    )
  )


write.csv(
  input_manifest,
  file.path(
    logs_dir,
    "138_input_file_manifest.csv"
  ),
  row.names = FALSE
)


# ==============================================================================
# 40. SESSION INFO
# ==============================================================================

capture.output(
  sessionInfo(),
  file = file.path(
    logs_dir,
    "138_sessionInfo.txt"
  )
)


# ==============================================================================
# 41. FINAL REPORT
# ==============================================================================

cat("\n")
cat("====================================================================\n")
cat("Script 138 completed successfully.\n")
cat("====================================================================\n\n")


cat("Main publication figures:\n\n")

cat("Figure 1: five-gene signature\n")
cat("Figure 2: SRS/CTS endotype hierarchy\n")
cat("Figure 3: five-gene endotype heatmap\n")
cat("Figure 4: clinical context\n")
cat("Figure 5: cross-signature convergence\n\n")


cat("Supplementary figures:\n\n")

cat("S1: demographic sensitivity\n")
cat("S2: contextual AUC benchmarking\n")
cat("S3: biomarker gene direction audit\n")
cat("S4: all signatures across CTS\n\n")


cat("Output folder:\n")

cat(
  normalizePath(
    output_dir,
    winslash = "/",
    mustWork = FALSE
  ),
  "\n\n"
)


cat("Figure formats:\n")
cat("- PNG: 600 dpi\n")
cat("- TIFF: 600 dpi, LZW compression\n")
cat("- PDF: vector format\n\n")


cat("Color system:\n")
cat("- BC = cyan-blue\n")
cat("- BP = red-orange\n")
cat("- SRS1 = orange-red\n")
cat("- SRS2 = blue\n")
cat("- CTS1 = amber\n")
cat("- CTS2 = light blue\n")
cat("- CTS3 = green\n\n")


cat("IMPORTANT:\n")
cat("- No new biomarker selection.\n")
cat("- No new prediction model.\n")
cat("- No urine.\n")
cat("- No lncRNA.\n")
cat("- Main biological story remains the host-response/endotype axis.\n")
cat("- AUC benchmarking remains Supplementary/contextual.\n\n")


cat("Done.\n")